### ISSUE TITLE
Feature: Publish on Play Store

### ISSUE THREAD

**Issue by theshininginception** [penguin86/ojo#18]
It would be great if Ojo could be published on the Play Store to expand reach to users and provide an easier way to keep the app updated.

**Comment by penguin86** [comment]
Hello @theshininginception ,
thank you for writing.

I decided to release Ojo as an F-Droid exclusive, so it cannot be published on Google Play.
This decision was made in the hope to help an healty ecosistem like F-Droid grow.
- F-Droid missed an RTSP viewer, while Play Store has a lot of proprietary closed-source alternatives: these may even be full of trackers, but the Play Services are full of trackers anyway, so I doubt it really makes a difference for the user
- Publishing an app on the Play Store isn't an healthy experience: I receive a lot of harsh reviews despite the effort I make in releasing good and privacy-respecting applications: I cannot compete with multi-milion companies, but dedicate almost all my free time to the open source community. Play Store also seems to not like open source projects and seems to penalise it. All this is hard on my feelings and it seems I'm not the only one (see FairEmail).
- F-Droid runs on almost all Android Phones, except the REALLY old ones, that couldn't support Ojo anyway. If for some reason one counldn't use F-Droid, can always download the APK from F-Droid web interface or from this repository, in the [releases](https://github.com/penguin86/ojo/releases) section.
 
If I can help in any other way, or you coundn't install the app for any reason, let me know, I'm here to help.
Hope you can understand.
Thank you!

**Comment by budnail** [comment]
I just wanted to say that I and others that I know personally really appreciate people like yourself who are putting in all the hard work it takes to make a useful app.  I put you right up there with the policemen, firefighters, and other first responders who generally only get noticed or singled out when something goes wrong.  The day-to-day work has to be its own reward because usually, that's all you get.  But in this case, you've actually accomplished something useful, not just put in the work. So thank you.
