### ISSUE TITLE
Support IPv6

### ISSUE THREAD

**Issue by BoostCookie** [penguin86/ojo#24]
If I insert my camera's IPv4 address it works, but if I insert its IPv6 address then it does not work.

**Comment by mooninite** [comment]
As also seen in an alternative app also using libVLC: https://github.com/vladpen/cams/issues/62

Upstream issue: https://code.videolan.org/videolan/vlc/-/issues/27623

The fix was tagged in version 4.0, but there is no known release date for VLC 4.0. Version 4.0 had a release date two years ago and it has been pushed back for two years and continues to be pushed back. FYI.

**Comment by penguin86** [comment]
Going to close this, for the moment, as the last version of libvlc is still 2.5.0 from 6 years ago.
