### ISSUE TITLE
Feature: Different stream for full screen view

### ISSUE THREAD

**Issue by katonagl** [penguin86/ojo#26]
For the grid view it is more than enough to use a substream of the cam, however for full screen it would be useful to use the main stream with full resolution. 
Just adding a second URL option to the camera setup would solve this.

Additionally zoom capability would also be useful for full screen view e.g. to look for details on a phone screen.

**Comment by penguin86** [comment]
Hello, this is a good idea, unfortunately this would require a massive app refactoring, as the video decoder and surfaceview used in the grid is the same that goes fullscreen when the tile is selected. Has been done this way because VLC needed some time to start streaming the video (some seconds), so selecting a tile would result in a black screen for some seconds.
I'm sorry, I don't plan to implement this ATM, but feel free to make a pull request if you can solve these issues.
Thank you!
